import { useEffect, useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { ArrowLeft, Bot, CheckCircle2, XCircle, Clock } from 'lucide-react'
import { ageApi } from '../../api'
import Button from '../../components/ui/Button'
import Card from '../../components/ui/Card'
import Badge from '../../components/ui/Badge'

/**
 * Static fallback bank of maturity questions. In production this should
 * be generated by Groq with rotating prompts to prevent answer leakage,
 * but a static bank is fine to ship the flow end-to-end.
 *
 * Each question has 4 options and a single correct index. Categories:
 *   L = legal-awareness, F = financial-literacy, C = civic, S = situational, H = health
 */
type Q = { q: string; opts: string[]; correct: number; cat: string }

const BANK: Q[] = [
  { q: 'Minimum age to sign a binding contract in India (without parental consent)?', opts: ['16', '17', '18', '21'], correct: 2, cat: 'L' },
  { q: 'GST stands for:', opts: ['General Sales Tax', 'Goods and Services Tax', 'Government Service Toll', 'Gross State Tax'], correct: 1, cat: 'F' },
  { q: 'A CIBIL score in India typically ranges from:', opts: ['0 to 100', '100 to 500', '300 to 900', '0 to 1000'], correct: 2, cat: 'F' },
  { q: 'Voter ID is issued by which body in India?', opts: ['RBI', 'SEBI', 'Election Commission', 'UIDAI'], correct: 2, cat: 'C' },
  { q: 'If you witness harassment at work, the most appropriate first step is to:', opts: ['Confront the harasser publicly', 'Document the incident and report through proper channels', 'Ignore it', 'Take revenge'], correct: 1, cat: 'S' },
  { q: 'Consent in a relationship can be withdrawn:', opts: ['Only at the start', 'Only in writing', 'At any time', 'Never once given'], correct: 2, cat: 'S' },
  { q: 'A passport in India is issued by:', opts: ['State Government', 'Ministry of External Affairs', 'RBI', 'Income Tax Dept'], correct: 1, cat: 'C' },
  { q: 'EMI primarily reflects:', opts: ['Pure interest', 'Pure principal', 'Principal + interest', 'A government subsidy'], correct: 2, cat: 'F' },
  { q: 'For your annual health check, the most useful baseline test is:', opts: ['MRI of the brain', 'Complete blood count + lipid profile', 'Bone density scan', 'CT angiography'], correct: 1, cat: 'H' },
  { q: 'The IT Act 2000 in India deals with:', opts: ['Income tax', 'Cybercrime and e-commerce', 'Foreign trade', 'Press freedom'], correct: 1, cat: 'L' },
  { q: 'If you find a lost wallet on the street, the right action is:', opts: ['Keep the cash, throw the wallet', 'Hand it to nearest police station / try to find owner', 'Post it on social media for fame', 'Leave it'], correct: 1, cat: 'S' },
  { q: 'In India, the legal driving age for a private car (gear) is:', opts: ['16', '17', '18', '21'], correct: 2, cat: 'L' },
  { q: 'A simple way to verify a news story is to:', opts: ['Trust the first WhatsApp forward', 'Check the source on multiple reputable outlets', 'Believe screenshots without checking', 'Share immediately if it feels right'], correct: 1, cat: 'C' },
  { q: 'If a friend confides they\'re feeling suicidal, the most responsible action is:', opts: ['Tell them to cheer up', 'Listen without judgement and help them reach a professional / helpline', 'Promise total secrecy with no follow-up', 'Avoid the conversation'], correct: 1, cat: 'H' },
  { q: 'A reasonable monthly emergency fund target is:', opts: ['No need for one', '1 day of expenses', '3-6 months of expenses', '10 years of expenses'], correct: 2, cat: 'F' },
  { q: 'Aadhaar is issued by:', opts: ['NPCI', 'UIDAI', 'TRAI', 'SEBI'], correct: 1, cat: 'C' },
  { q: 'A police FIR can normally be filed at:', opts: ['Any local court', 'The nearest police station', 'The RBI', 'A municipal office'], correct: 1, cat: 'L' },
  { q: 'Adults living together typically split shared expenses by:', opts: ['Whoever earns less pays nothing', 'Mutual agreement based on incomes / fairness', 'Always 50/50 regardless of income', 'One person silently absorbs all costs'], correct: 1, cat: 'S' },
  { q: 'A safe annual sun-exposure habit includes:', opts: ['No sunscreen ever', 'Sunscreen + limiting peak hours', 'Tanning beds daily', 'Avoiding outdoors entirely'], correct: 1, cat: 'H' },
  { q: 'When buying property in India, the most important document to verify is:', opts: ['Title deed and encumbrance certificate', 'A photo of the building', 'The owner\'s favourite colour', 'WhatsApp chat with broker'], correct: 0, cat: 'L' },
]

const QUESTIONS_PER_SESSION = 15
const SECONDS_PER_QUESTION = 10
const PASS_PERCENT = 70 // 70% of 15 = 10.5 → need 11/15

export default function AiQuizPage() {
  const navigate = useNavigate()

  // One-shot random sample at mount; never reshuffles mid-session.
  const session = useMemo(() => {
    const shuffled = [...BANK].sort(() => Math.random() - 0.5).slice(0, QUESTIONS_PER_SESSION)
    return shuffled.map((q) => {
      // Shuffle option order, remember new correct index.
      const indices = q.opts.map((_, i) => i).sort(() => Math.random() - 0.5)
      const opts = indices.map((i) => q.opts[i])
      const correct = indices.indexOf(q.correct)
      return { q: q.q, opts, correct, cat: q.cat }
    })
  }, [])

  const [idx, setIdx] = useState(0)
  const [answers, setAnswers] = useState<(number | null)[]>(
    () => Array(QUESTIONS_PER_SESSION).fill(null),
  )
  const [timeLeft, setTimeLeft] = useState(SECONDS_PER_QUESTION)
  const [done, setDone] = useState(false)
  const [submitting, setSubmitting] = useState(false)
  const [result, setResult] = useState<{ passed: boolean; attemptsRemaining: number; message: string } | null>(null)

  /* Per-question countdown */
  useEffect(() => {
    if (done) return
    setTimeLeft(SECONDS_PER_QUESTION)
    const t = window.setInterval(() => {
      setTimeLeft((s) => {
        if (s <= 1) {
          window.clearInterval(t)
          advance()
          return 0
        }
        return s - 1
      })
    }, 1000)
    return () => window.clearInterval(t)
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [idx, done])

  const pick = (optIdx: number) => {
    if (done) return
    setAnswers((prev) => {
      const next = [...prev]
      next[idx] = optIdx
      return next
    })
    // Small UX delay so the user sees the choice register, then advance.
    window.setTimeout(advance, 200)
  }

  const advance = () => {
    if (idx + 1 < QUESTIONS_PER_SESSION) {
      setIdx(idx + 1)
    } else {
      submitResults()
    }
  }

  const submitResults = async () => {
    if (submitting || done) return
    setSubmitting(true)
    setDone(true)

    const correctCount = session.reduce((acc, q, i) => acc + (answers[i] === q.correct ? 1 : 0), 0)
    const finalScore = Math.round((correctCount / QUESTIONS_PER_SESSION) * 100)

    try {
      const res = await ageApi.submitAiQuiz({
        finalScore,
        questions: session.map((q, i) => ({
          category: q.cat,
          submitted: answers[i],
          correct: q.correct,
        })),
      })
      const data = res.data.data
      setResult({
        passed: !!data.passed,
        attemptsRemaining: data.attemptsRemaining ?? 0,
        message: data.message ?? '',
      })
    } catch (err: any) {
      setResult({
        passed: false,
        attemptsRemaining: 0,
        message: err.response?.data?.error ?? 'Failed to submit. Try again later.',
      })
    } finally {
      setSubmitting(false)
    }
  }

  /* Result view */
  if (result) {
    return (
      <div className="h-full overflow-y-auto bg-[var(--color-bg)] text-[var(--color-fg)]">
        <div className="max-w-md mx-auto px-6 py-12 text-center">
          <div className={`inline-flex items-center justify-center w-16 h-16 rounded-full border mb-5
            ${
              result.passed
                ? 'bg-[var(--color-success-soft)] border-[var(--color-success-border)] text-[var(--color-success-fg)]'
                : 'bg-[var(--color-warning-soft)] border-[var(--color-warning-border)] text-[var(--color-warning-fg)]'
            }`}>
            {result.passed ? <CheckCircle2 size={26} /> : <XCircle size={26} />}
          </div>
          <h2 className="text-2xl font-semibold tracking-tight mb-2">
            {result.passed ? 'Passed!' : 'Didn\'t pass'}
          </h2>
          <p className="text-sm text-[var(--color-fg-faint)] mb-6 leading-relaxed">
            {result.message}
          </p>
          {result.passed ? (
            <Button fullWidth size="lg" onClick={() => navigate('/verify/document')}>
              Continue to last step
            </Button>
          ) : (
            <Button
              fullWidth
              size="lg"
              variant="subtle"
              onClick={() => navigate('/profile')}
            >
              Back to profile
            </Button>
          )}
          {!result.passed && result.attemptsRemaining > 0 && (
            <p className="mt-3 text-xs text-[var(--color-fg-mute)]">
              Try again after the cooldown ({result.attemptsRemaining} attempts remaining).
            </p>
          )}
        </div>
      </div>
    )
  }

  const current = session[idx]
  const selected = answers[idx]

  return (
    <div className="h-full overflow-y-auto bg-[var(--color-bg)] text-[var(--color-fg)]">
      <div className="max-w-xl mx-auto px-6 py-8">
        <button
          onClick={() => navigate('/profile')}
          className="inline-flex items-center gap-1.5 text-xs text-[var(--color-fg-faint)] hover:text-[var(--color-fg)] mb-6 transition-colors"
        >
          <ArrowLeft size={13} />
          Quit quiz
        </button>

        <div className="flex items-center justify-between mb-3">
          <div className="flex items-center gap-2">
            <Bot size={16} className="text-[var(--color-accent-fg)]" />
            <span className="text-sm font-medium">AI maturity assessment</span>
          </div>
          <Badge tone="neutral" size="sm">
            Question {idx + 1} / {QUESTIONS_PER_SESSION}
          </Badge>
        </div>

        {/* Progress bar */}
        <div className="w-full h-1 bg-[var(--color-surface-2)] rounded-full overflow-hidden mb-6">
          <div
            className="h-full bg-[var(--color-accent)] transition-all duration-300"
            style={{ width: `${((idx + 1) / QUESTIONS_PER_SESSION) * 100}%` }}
          />
        </div>

        <Card padding="lg">
          <div className="flex items-center justify-between mb-4">
            <Badge tone="accent" size="sm" dot>
              {{ L: 'Legal', F: 'Financial', C: 'Civic', S: 'Situational', H: 'Health' }[current.cat] ?? current.cat}
            </Badge>
            <div
              className={`flex items-center gap-1.5 text-xs tabular-nums
                ${timeLeft <= 3 ? 'text-[var(--color-danger)]' : 'text-[var(--color-fg-faint)]'}`}
            >
              <Clock size={12} />
              {timeLeft}s
            </div>
          </div>

          <h2 className="text-base font-medium leading-relaxed mb-5">
            {current.q}
          </h2>

          <div className="space-y-2">
            {current.opts.map((opt, optIdx) => {
              const isPicked = selected === optIdx
              return (
                <button
                  key={optIdx}
                  onClick={() => pick(optIdx)}
                  disabled={selected !== null}
                  className={`w-full p-3 rounded-md border text-left text-sm transition-colors
                    ${
                      isPicked
                        ? 'bg-[var(--color-accent-soft)] border-[var(--color-accent)] text-[var(--color-fg)]'
                        : 'bg-[var(--color-surface-2)] border-[var(--color-line)] hover:bg-[var(--color-surface-3)] hover:border-[var(--color-line-strong)] text-[var(--color-fg)]'
                    }
                    disabled:cursor-not-allowed`}
                >
                  {opt}
                </button>
              )
            })}
          </div>
        </Card>

        <p className="mt-4 text-center text-[11px] text-[var(--color-fg-mute)]">
          Pass with {PASS_PERCENT}% or better. Up to 3 attempts per cooldown window.
        </p>
      </div>
    </div>
  )
}
